version: "3.8"

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      # Updated: Use the docker-compose service name and internal port for chroma
      - CHROMADB_URL=http://chroma:8000
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    ports:
      - "8002:8000"