version: "3.8"

services:
  app:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      # This env variable will be used in your Node code.
      - CHROMADB_URL=http://chroma:8002
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:3002", "https://agent-api-vectorstore.ai.amalgamrx.com"]
    ports:
      - "8002:8000"